### ISSUE TITLE
Not working with SSL?

### ISSUE THREAD

**Issue by rsteckler** [payano/homeassist-ng#12]
I'm using an SSL certificate and an API key.  Can't seem to log in because it fails with incorrect password error.  Is ssl supported?

**Comment by rsteckler** [comment]
Just checked on the original Home Assist and the exact same url/password works there.  Definitely an app issue.

**Comment by payano** [comment]
Strange, I am using https to my home assistant server. Does http work?

I wrote this guide on how to setup the client and the server: https://github.com/payano/homeassist-ng/wiki/Configure-HomeAssistant-with-HomeAssist-ng

**Comment by Andoramb** [comment]
Works for me after the setup guide ^_^
